services:
  mcp:
    build:
      context: .
      dockerfile: ./mcp_service/Dockerfile
    environment:
      API_URL: http://api:8000
      OTLP_TRACES_ENDPOINT: http://alloy:4318/v1/traces
    ports:
      - "9000:9000"
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: ./api_service/Dockerfile
    environment:
      ENV: production
      OTLP_TRACES_ENDPOINT: http://alloy:4318/v1/traces
      REDIS_URL: redis://redis:6379
      DB_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
  worker:
    build:
      context: .
      dockerfile: ./worker_service/Dockerfile
    env_file:
      - .env
    environment:
      ENV: production
      OTLP_TRACES_ENDPOINT: http://alloy:4318/v1/traces
      REDIS_URL: redis://redis:6379
      DB_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  ngrok:
    image: ngrok/ngrok:latest
    command: http mcp:9000
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    depends_on:
      - mcp

  alloy:
    image: grafana/alloy:latest
    command:
      - run
      - /etc/alloy/config.alloy
    volumes: 
      - ./tracing/alloy/config.alloy:/etc/alloy/config.alloy
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - tempo

  tempo:
    image: grafana/tempo:2.10.0
    command:
      - "-config.file=/etc/tempo/tempo.yaml"
    volumes:
      - ./tracing/tempo/tempo.yaml:/etc/tempo/tempo.yaml
    ports:
      - "3200:3200"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - tempo
