FROM python:3.12-slim

WORKDIR /app

COPY worker/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY worker /app/worker
COPY common /app/common

CMD ["python", "-m", "worker.job_executer.py"]